// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcbkuiqwodycflzfxcks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjYmt1aXF3b2R5Y2ZsemZ4Y2tzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NTE0ODYsImV4cCI6MjA1OTEyNzQ4Nn0.NjoLCouC8g2ul1IrTjQYYQLAnW0Cm2g_nr5QGf3XJ6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);